version: '2'
services:
  netbox:
    image: ninech/netbox
    depends_on:
    - postgres
    environment:
      TZ: ${netbox_timezone}
      ALLOWED_HOSTS: ${netbox_allowed_hosts}
      DB_NAME: ${netbox_db_name}
      DB_USER: ${netbox_db_user}
      DB_PASSWORD: ${netbox_db_password}
      DB_HOST: postgres
      EMAIL_SERVER: ${netbox_email_server}
      EMAIL_PORT: ${netbox_email_server_port}
      EMAIL_USERNAME: ${netbox_email_user}
      EMAIL_PASSWORD: ${netbox_email_password}
      EMAIL_TIMEOUT: ${netbox_email_timeout}
      EMAIL_FROM: ${netbox_email_from}
      NAPALM_TIMEOUT: ${netbox_napalm_timeout}
      MAX_PAGE_SIZE: ${netbox_max_page_size}
      SECRET_KEY: ${netbox_secret_key}
      SUPERUSER_NAME: ${netbox_superuser_name}
      SUPERUSER_EMAIL: ${netbox_superuser_email}
      SUPERUSER_PASSWORD: ${netbox_superuser_password}
      SUPERUSER_API_TOKEN: ${netbox_superuser_apitoken}
    volumes_from:
    - netbox-data
  nginx:
    image: nginx:1.13-alpine
    labels:
      io.rancher.sidekicks: netbox, netbox-data, postgres
      {{- if ne .Values.requested_ip ""}}
      io.rancher.container.requested_ip: ${requested_ip}
      {{- end}}
    command: nginx -g 'daemon off;' -c /etc/netbox-nginx/nginx.conf
    hostname: ${netbox_hostname}
    depends_on:
    - netbox
    ports:
    - ${http_port}:8080/tcp
    volumes_from:
    - netbox-data
  postgres:
    image: postgres:10.2-alpine
    environment:
      POSTGRES_USER: ${netbox_db_user}
      POSTGRES_PASSWORD: ${netbox_db_password}
      POSTGRES_DB: ${netbox_db_name}
    volumes_from:
    - netbox-data
  netbox-data:
    labels:
      io.rancher.container.start_once: 'true'
    image: busybox
    network_mode: none
    entrypoint:
    - /bin/true
    volume_driver: ${volume_driver}
    volumes:
    - /etc/netbox:ro
    - /etc/netbox-nginx
    - /opt/netbox
    - /var/lib/postgresql/data
