.catalog:
  name: Netbox
  version: v2.3.0
  description: |
    NetBox is an open source web application designed to help manage and document computer networks. 
  minimum_rancher_version: v0.56.0
  maintainer: "shawly <shawlyde@gmail.com>"
  uuid: netbox-0
  questions:
    - variable: "netbox_hostname"
      description: "Netbox hostname"
      label: "Hostname:"
      required: true
      default: "netbox.example.com"
      type: "string"
    - variable: "http_port"
      description: "HTTP port to expose on host. Will be used to bind TCP"
      label: "HTTP port:"
      required: true
      default: 8080
      type: "string"
    - variable: "requested_ip"
      description: "Static IP for the container"
      label: "Static IP:"
      required: false
      default: ""
      type: "string"
    - variable: "netbox_timezone"
      description: "Timezone for Netbox."
      label: "Timezone:"
      required: true
      default: "Europe/Berlin"
      type: "string"
    - variable: "netbox_allowed_hosts"
      description: "Allowed hosts."
      label: "Allowed hosts:"
      required: true
      default: "localhost 0.0.0.0 127.0.0.1 [::1] netbox nginx netboxdocker.docker nginx.netboxdocker.docker"
      type: "string"
    - variable: "netbox_db_name"
      description: "Postgres DB name for Netbox."
      label: "DB name:"
      required: true
      default: "netbox"
      type: "string"
    - variable: "netbox_db_user"
      description: "Postgres DB user for Netbox."
      label: "DB user:"
      required: true
      default: "netbox"
      type: "string"
    - variable: "netbox_db_password"
      description: "Postgres DB password for Netbox. (default: netbox)"
      label: "DB password:"
      required: true
      default: "netbox"
      type: "password"
    - variable: "netbox_email_server"
      description: "Email server for Netbox"
      label: "Email server:"
      required: true
      default: "localhost"
      type: "string"
    - variable: "netbox_email_server_port"
      description: "Email server port for Netbox"
      label: "Email server port:"
      required: true
      default: "25"
      type: "string"
    - variable: "netbox_email_user"
      description: "Email server user for Netbox"
      label: "Email server username:"
      required: true
      default: "netbox"
      type: "string"
    - variable: "netbox_email_password"
      description: "Email server password for Netbox"
      label: "Email server password:"
      required: false
      default: ""
      type: "password"
    - variable: "netbox_email_timeout"
      description: "Email server timeout for Netbox"
      label: "Email server timeout:"
      required: true
      default: "5"
      type: "string"
    - variable: "netbox_email_from"
      description: "Email from for Netbox"
      label: "Email from:"
      required: true
      default: "netbox@bar.com"
      type: "string"
    - variable: "netbox_napalm_timeout"
      description: "Napalm timeout"
      label: "Napalm timeout:"
      required: true
      default: "5"
      type: "string"
    - variable: "netbox_max_page_size"
      description: "Maximum page size"
      label: "Max page size:"
      required: true
      default: "0"
      type: "string"
    - variable: "netbox_secret_key"
      description: "Secret key"
      label: "Secret key:"
      required: true
      default: "r8OwDznj!!dci#P9ghmRfdu1Ysxm0AiPeDCQhKE+N_rClfWNj"
      type: "string"
    - variable: "netbox_superuser_name"
      description: "Superuser username for Netbox"
      label: "Superuser:"
      required: true
      default: "admin"
      type: "string"
    - variable: "netbox_superuser_email"
      description: "Superuser email for Netbox"
      label: "Superuser email:"
      required: true
      default: "admin@example.com"
      type: "string"
    - variable: "netbox_superuser_password"
      description: "Superuser password for Netbox (default: admin)"
      label: "Superuser password:"
      required: true
      default: "admin"
      type: "password"
    - variable: "netbox_superuser_apitoken"
      description: "Superuser API token for Netbox)"
      label: "Superuser API token:"
      required: true
      default: "0123456789abcdef0123456789abcdef01234567"
      type: "string"
    - variable: "volume_driver"
      description: "Volume driver for Netbox data."
      label: "Volume Driver:"
      required: true
      default: "local"
      type: "string"

nginx:
  scale: 1
  retain_ip: true
  health_check:
    port: 8080
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
netbox:
  scale: 1
postgres:
  scale: 1
netbox-data:
  scale: 1
