version: '2'
services:
  organizr:
    ports:
    - ${http_port}:80/tcp
    labels:
      io.rancher.sidekicks: organizr-data
      {{- if ne .Values.requested_ip ""}}
      io.rancher.container.requested_ip: ${requested_ip}
      {{- end}}
    hostname: ${organizr_hostname}
    image: lsiocommunity/organizr
    environment:
      TZ: ${organizr_timezone}
    volumes_from:
    - organizr-data
  organizr-data:
    labels:
      io.rancher.container.start_once: 'true'
    image: busybox
    network_mode: none
    entrypoint:
    - /bin/true
    volume_driver: ${volume_driver}
    volumes:
    - /config
