name: Keeweb
description: |
  This webapp is a browser and desktop password manager compatible with KeePass databases. It doesn't require any server or additional resources.
version: 1.6.3
category: Applications
