version: '2'
services:
  dokuwiki:
    ports:
    - ${http_port}:80/tcp
    - ${https_port}:443/tcp
    labels:
      io.rancher.sidekicks: dokuwiki-data
      {{- if ne .Values.requested_ip ""}}
      io.rancher.container.requested_ip: ${requested_ip}
      {{- end}}
    hostname: ${dokuwiki_hostname}
    image: bitnami/dokuwiki
    volumes_from:
    - dokuwiki-data
    environment:
      DOKUWIKI_FULL_NAME: ${dokuwiki_full_name}
      DOKUWIKI_USERNAME: ${dokuwiki_username}
      DOKUWIKI_PASSWORD: ${dokuwiki_password}
      DOKUWIKI_EMAIL: ${dokuwiki_email}
      DOKUWIKI_WIKI_NAME: ${dokuwiki_wiki_name}
  dokuwiki-data:
    labels:
      io.rancher.container.start_once: 'true'
    entrypoint:
    - /bin/true
    image: busybox
    volume_driver: ${volume_driver}
    volumes:
    - /bitnami
