.catalog:
  name: Dokuwiki
  version: 2016-06-26a
  description: |
    DokuWiki is a simple to use and highly versatile Open Source wiki software that doesn't require a database.
  minimum_rancher_version: v0.56.0
  maintainer: "shawly <shawlyde@gmail.com>"
  uuid: dokuwiki-0
  questions:
    - variable: "dokuwiki_hostname"
      description: "Dokuwiki hostname"
      label: "Hostname:"
      required: true
      default: "dokuwiki.example.com"
      type: "string"
    - variable: "http_port"
      description: "HTTP port to expose on host. Will be used to bind TCP"
      label: "HTTP port:"
      required: true
      default: 80
      type: "string"
    - variable: "https_port"
      description: "HTTPS port to expose on host. Will be used to bind TCP"
      label: "HTTPS port:"
      required: true
      default: 443
      type: "string"
    - variable: "requested_ip"
      description: "Static IP for the container"
      label: "Static IP:"
      required: false
      default: ""
      type: "string"
    - variable: "dokuwiki_full_name"
      description: "The full name of the DokuWiki admin account."
      label: "Full Name:"
      required: true
      default: "Full Name"
      type: "string"
    - variable: "dokuwiki_username"
      description: "The username of the DokuWiki admin account."
      label: "Username:"
      required: true
      default: "superuser"
      type: "string"
    - variable: "dokuwiki_password"
      description: "The password of the DokuWiki admin account. Default is bitnami1."
      label: "Password:"
      required: true
      default: "bitnami1"
      type: "password"
    - variable: "dokuwiki_email"
      description: "The email of the DokuWiki admin account."
      label: "Email:"
      required: true
      default: "user@example.com"
      type: "string"
    - variable: "dokuwiki_wiki_name"
      description: "The site name of the DokuWiki."
      label: "Wiki Name:"
      required: true
      default: "Bitnami DokuWiki"
      type: "string"
    - variable: "volume_driver"
      description: "Volume driver for dokuwiki data."
      label: "Volume Driver:"
      required: true
      default: "local"
      type: "string"


dokuwiki:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2

dokuwiki-data:
  scale: 1
