name: McMyAdmin2
description: |
  McMyAdmin is the leading web control panel and administration console for Minecraft servers, trusted by over 75000 server admins and more than 35 different service providers. McMyAdmin makes it easy for you to control your Minecraft servers via it's straight forward user interface and mobile apps.
version: 2.7.0.2
category: Entertainment
