.catalog:
  name: KeeWeb
  version: 1.6.3
  description: |
    This webapp is a browser and desktop password manager compatible with KeePass databases. It doesn't require any server or additional resources.
  minimum_rancher_version: v0.56.0
  maintainer: "shawly <shawlyde@gmail.com>"
  uuid: keeweb-0
  questions:
    - variable: "keeweb_hostname"
      description: "KeeWeb hostname"
      label: "Hostname:"
      required: true
      default: "keeweb.example.com"
      type: "string"
    - variable: "http_port"
      description: "HTTP port to expose on host. Will be used to bind TCP"
      label: "HTTP port:"
      required: true
      default: 80
      type: "string"
    - variable: "https_port"
      description: "HTTPS port to expose on host. Will be used to bind TCP"
      label: "HTTPS port:"
      required: true
      default: 443
      type: "string"
    - variable: "requested_ip"
      description: "Static IP for the container"
      label: "Static IP:"
      required: false
      default: ""
      type: "string"
    - variable: "keeweb_timezone"
      description: "Timezone for KeeWeb."
      label: "Timezone:"
      required: true
      default: "Europe/Berlin"
      type: "string"
    - variable: "volume_driver"
      description: "Volume driver for KeeWeb data."
      label: "Volume Driver:"
      required: true
      default: "local"
      type: "string"

keeweb:
  scale: 1
  retain_ip: true
  health_check:
    port: 80
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
keeweb-data:
  scale: 1
