name: Home Assistant
description: |
  Home Assistant is a home automation platform running on Python 3. It is able to track and control all devices at home and offer a platform for automating control.
version: 0.63.2
category: Smarthome
