version: '2'
services:
  plex-media-server:
    ports:
    - ${plex_port}:32400/tcp
    - 3005:3005/tcp
    - 8324:8324/tcp
    - 32469:32469/tcp
    - 1900:1900/udp
    - 32410:32410/udp
    - 32412:32412/udp
    - 32413:32413/udp
    - 32414:32414/udp
    labels:
      io.rancher.sidekicks: plex-media-server-data
      {{- if ne .Values.requested_ip ""}}
      io.rancher.container.requested_ip: ${requested_ip}
      {{- end}}
    hostname: ${plex_hostname}
    image: plexinc/pms-docker
    environment:
      TZ: ${plex_timezone}
      CLAIM_TOKEN: ${plex_claimtoken}
      ADVERTISE_IP: http://${requested_ip}:${plex_port}/
    volumes_from:
    - plex-media-server-data
  plex-media-server-data:
    labels:
      io.rancher.container.start_once: 'true'
    image: busybox
    network_mode: none
    entrypoint: ["chown", "-R", "1000:100", "/config", "/transcode"]
    volume_driver: ${volume_driver}
    volumes:
    - /config
    - /transcode
