name: Filebot
description: |
  FileBot is the ultimate tool for organizing and renaming your movies, tv shows or anime, and music well as downloading subtitles and artwork. It's smart and just works.
version: 1.0.2
category: Applications
