version: '2'
services:
  pi-hole:
    ports:
    - ${dns_port}:53/tcp
    - ${dns_port}:53/udp
    - ${http_port}:80/tcp
    labels:
      io.rancher.sidekicks: pi-hole-data
      {{- if ne .Values.requested_ip ""}}
      io.rancher.container.requested_ip: ${requested_ip}
      {{- end}}
    cap_add:
    - NET_ADMIN
    hostname: ${pihole_hostname}
    image: diginc/pi-hole
    environment:
      ServerIP: ${pihole_server_ip}
      TZ: ${pihole_timezone}
      WEBPASSWORD: ${pihole_password}
      DNS1: ${pihole_dns1}
      DNS2: ${pihole_dns2}
      VIRTUAL_HOST: ${pihole_virtual_host}
      IPv6: ${pihole_ipv6}
      INTERFACE: ${pihole_interface}
      DNSMASQ_LISTENING: ${pihole_dnsmasqlistening}
      WEB_PORT: ${http_port}
    extra_hosts:
    - ${pihole_hostname}:${pihole_server_ip}
    volumes_from:
    - pi-hole-data
  pi-hole-data:
    labels:
      io.rancher.container.start_once: 'true'
    image: busybox
    network_mode: none
    entrypoint:
    - /bin/true
    volume_driver: ${volume_driver}
    volumes:
    - /etc/pihole
    - /etc/dnsmasq.d
