version: '2'
services:
  filebot:
    ports:
    - ${http_port}:5800/tcp
    - ${vnc_port}:5900/tcp
    labels:
      io.rancher.sidekicks: filebot-data
      {{- if ne .Values.requested_ip ""}}
      io.rancher.container.requested_ip: ${requested_ip}
      {{- end}}
    hostname: ${filebot_hostname}
    image: jlesage/filebot
    environment:
      TZ: ${filebot_timezone}
      KEEP_APP_RUNNING: ${filebot_keepapprunning}
      CLEAN_TMP_DIR: ${filebot_cleantmpdir}
      DISPLAY_WIDTH: ${filebot_display_width}
      DISPLAY_HEIGHT: ${filebot_display_height}
      SECURE_CONNECTION: ${filebot_secure_connection}
      {{- if ne .Values.filebot_vnc_password ""}}
      VNC_PASSWORD: ${filebot_vnc_password}
      {{- end}}
    volumes_from:
    - filebot-data
  filebot-data:
    labels:
      io.rancher.container.start_once: 'true'
    image: busybox
    network_mode: none
    entrypoint: ["chown", "-R", "1000:1000", "/config", "/storage"]
    volume_driver: ${volume_driver}
    volumes:
    - /config
    - filebot_data:/storage
volumes:
  filebot_data:
    driver: ${volume_driver}
    {{- if eq .Values.volume_custom_export "true"}}
    driver_opts:
      host: ${volume_export_host}
      {{- if eq .Values.volume_export_type "export"}}
      export: ${volume_export_path}
      {{- else }}
      exportBase: ${volume_export_path}
      {{- end}}
    {{- end}}
