version: '2'
services:
  syncthing:
    ports:
    - ${http_port}:8384/tcp
    - ${syncthing_port}:22000/tcp
    - ${syncthing_discovery_port}:21027/udp
    labels:
      io.rancher.sidekicks: syncthing-data
      {{- if ne .Values.requested_ip ""}}
      io.rancher.container.requested_ip: ${requested_ip}
      {{- end}}
    hostname: ${syncthing_hostname}
    image: syncthing/syncthing
    environment:
      TZ: ${syncthing_timezone}
    volumes_from:
    - syncthing-data
  syncthing-data:
    labels:
      io.rancher.container.start_once: 'true'
    image: busybox
    entrypoint:
    - /bin/true
    volume_driver: ${volume_driver}
    volumes:
    - /var/syncthing/config
    - ${syncvolume_name}:/var/syncthing/sync
volumes:
  ${syncvolume_name}:
    {{- if eq .Values.volume_custom_export "true"}}
    driver_opts:
      host: ${volume_host}
      ${volume_export_type}: ${volume_export}
    {{- end}}
