.catalog:
  name: Syncthing
  version: 0.14.45-rc.3
  description: |
    Syncthing is a continuous file synchronization program. It synchronizes files between two or more computers.
  minimum_rancher_version: v0.56.0
  maintainer: "shawly <shawlyde@gmail.com>"
  uuid: syncthing-0
  questions:
    - variable: "syncthing_hostname"
      description: "Syncthing hostname"
      label: "Hostname:"
      required: true
      default: "syncthing.example.com"
      type: "string"
    - variable: "http_port"
      description: "HTTP port to expose on host. Will be used to bind TCP"
      label: "HTTP port:"
      required: true
      default: 8384
      type: "string"
    - variable: "syncthing_port"
      description: "Syncthing port to expose on host. Will be used to bind TCP"
      label: "Syncthing port:"
      required: true
      default: 22000
      type: "string"
    - variable: "syncthing_discovery_port"
      description: "Syncthing Discovery port to expose on host. Will be used to bind UDP"
      label: "Syncthing discovery port:"
      required: true
      default: 21027
      type: "string"
    - variable: "requested_ip"
      description: "Static IP for the container"
      label: "Static IP:"
      required: false
      default: ""
      type: "string"
    - variable: "syncthing_timezone"
      description: "Timezone for Syncthing."
      label: "Timezone:"
      required: true
      default: "Europe/Berlin"
      type: "string"
    - variable: "volume_driver"
      description: "Volume driver for Syncthing data."
      label: "Volume Driver:"
      required: true
      default: "local"
      type: "string"
    - variable: "volume_name"
      description: "Volume name for sync folder."
      label: "Volume Name:"
      required: true
      default: "syncthing_data"
      type: "string"
    - variable: "volume_custom_export"
      description: "Use custom volume export? For usage with rancher-nfs."
      label: "Use Custom Export:"
      required: false
      default: false
      type: "boolean"
    - variable: "volume_export_host"
      description: "Export host for custom export."
      label: "Export Host:"
      required: false
      default: "192.168.0.100"
      type: "string"
    - variable: "volume_export_type"
      description: "Export type for custom export."
      label: "Export Type:"
      required: false
      default: "export"
      type: enum   
      options:
        - export
        - exportBase
    - variable: "volume_export_path"
      description: "Export path for custom export."
      label: "Export Path:"
      required: false
      default: "/export/syncthing"
      type: "string"

syncthing:
  scale: 1
  retain_ip: true
  health_check:
    port: 8384
    interval: 30000
    unhealthy_threshold: 3
    strategy: recreate
    response_timeout: 2000
    healthy_threshold: 2
syncthing-data:
  scale: 1
